In [4]:
# - Separar Dados (Train, Test)
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [6]:
# Carregar seu dataframe (substitua 'seu_dataframe.csv' pelo caminho do seu arquivo CSV)
df = pd.read_excel("dados.xlsx")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   DATA_VENDA               986 non-null    object
 1   MODELO                   986 non-null    object
 2   KM-LITRO                 984 non-null    float64
 3   CILINDROS                986 non-null    int64
 4   PESO(KG)                 986 non-null    int64
 5   VELOCIDADE_MAXIMA(KM/H)  986 non-null    int64
 6   CAVALOS                  986 non-null    int64
 7   TRANSMISSAO              986 non-null    object
 8   VALOR                    986 non-null    object
 9   CATEGORIA                986 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 77.2+ KB

In [8]:
df.head()

,DATA_VENDA,MODELO,KM-LITRO,CILINDROS,PESO(KG),VELOCIDADE_MAXIMA(KM/H),CAVALOS,TRANSMISSAO,VALOR,CATEGORIA
0,10/1/2020,LABORGUINI,3.0,12,1200,360,700,AUTOMATICO,50000000,IMPORTADO
1,10/1/2020,LABORGUINI,3.0,12,1200,360,700,AUTOMATICO,50000000,IMPORTADO
2,10/1/2020,LABORGUINI,3.0,12,1200,360,700,AUTOMATICO,900000,IMPORTADO
3,10/1/2020,FERRARI,3.0,12,1400,360,640,AUTOMATICO,900000,IMPORTADO
4,10/1/2020,ASTON MARTIN,3.5,10,1600,360,620,AUTOMATICO,900000,IMPORTADO

In [9]:
# Definir a proporção de treinamento (por exemplo, 80%) e teste (por exemplo, 20%)
percent_treino = 0.8

# Dividir o dataframe em conjuntos de treinamento e teste - Aleatorio
df_treino, df_teste = train_test_split(df, train_size=percent_treino, random_state=42)

In [10]:
df_treino.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 788 entries, 762 to 102
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   DATA_VENDA               788 non-null    object
 1   MODELO                   788 non-null    object
 2   KM-LITRO                 786 non-null    float64
 3   CILINDROS                788 non-null    int64
 4   PESO(KG)                 788 non-null    int64
 5   VELOCIDADE_MAXIMA(KM/H)  788 non-null    int64
 6   CAVALOS                  788 non-null    int64
 7   TRANSMISSAO              788 non-null    object
 8   VALOR                    788 non-null    object
 9   CATEGORIA                788 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 67.7+ KB

In [11]:
df_teste.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 198 entries, 613 to 964
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   DATA_VENDA               198 non-null    object
 1   MODELO                   198 non-null    object
 2   KM-LITRO                 198 non-null    float64
 3   CILINDROS                198 non-null    int64
 4   PESO(KG)                 198 non-null    int64
 5   VELOCIDADE_MAXIMA(KM/H)  198 non-null    int64
 6   CAVALOS                  198 non-null    int64
 7   TRANSMISSAO              198 non-null    object
 8   VALOR                    198 non-null    object
 9   CATEGORIA                198 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 17.0+ KB

In [12]:
df_treino.head()

,DATA_VENDA,MODELO,KM-LITRO,CILINDROS,PESO(KG),VELOCIDADE_MAXIMA(KM/H),CAVALOS,TRANSMISSAO,VALOR,CATEGORIA
762,10/10/2021,ASTON MARTIN,3.5,10,1600,360,620,AUTOMATICO,900000,IMPORTADO
334,10/10/2020,HONDA FIT,12.0,4,1700,200,116,AUTOMATICO,120000,NACIONAL
890,10/12/2021,HB20,9.0,3,2100,200,118,MANUAL,40000,NACIONAL
529,10/4/2021,LABORGUINI,3.0,12,1200,360,700,AUTOMATICO,900000,IMPORTADO
468,10/1/2021,UNO,13.5,4,1700,200,118,MANUAL,48000,NACIONAL

In [14]:
df_teste.head()

,DATA_VENDA,MODELO,KM-LITRO,CILINDROS,PESO(KG),VELOCIDADE_MAXIMA(KM/H),CAVALOS,TRANSMISSAO,VALOR,CATEGORIA
613,10/7/2021,CORSA,9.0,4,1900,200,118,MANUAL,35000,NACIONAL
451,10/12/2020,HB20,9.0,3,2100,200,118,MANUAL,40000,NACIONAL
731,10/9/2021,PARATI,11.0,4,2400,220,118,MANUAL,18000,NACIONAL
436,10/12/2020,HONDA FIT,12.0,4,1700,200,116,AUTOMATICO,120000,NACIONAL
275,10/9/2020,MOBI,14.0,4,1700,200,118,MANUAL,42000,NACIONAL

In [15]:
# Agora você tem o dataframe de treinamento (df_treino) e o dataframe de teste (df_teste)
# Se você quiser dividir o dataframe igualmente em vez de usar uma proporção, pode fazer algo assim:

# Obter o número de linhas do dataframe
num_linhas = len(df)

# Definir o número de linhas para cada conjunto (por exemplo, 50% para cada)
num_linhas_treino = int(num_linhas * 0.5)

# Embaralhar o dataframe para garantir que as linhas sejam selecionadas aleatoriamente
df = df.sample(frac=1, random_state=42)

# Dividir o dataframe igualmente
df_treino = df.iloc[:num_linhas_treino]
df_teste = df.iloc[num_linhas_treino:]

In [16]:
df_treino.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 493 entries, 613 to 335
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   DATA_VENDA               493 non-null    object
 1   MODELO                   493 non-null    object
 2   KM-LITRO                 492 non-null    float64
 3   CILINDROS                493 non-null    int64
 4   PESO(KG)                 493 non-null    int64
 5   VELOCIDADE_MAXIMA(KM/H)  493 non-null    int64
 6   CAVALOS                  493 non-null    int64
 7   TRANSMISSAO              493 non-null    object
 8   VALOR                    493 non-null    object
 9   CATEGORIA                493 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 42.4+ KB

In [17]:
df_teste.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 493 entries, 606 to 102
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   DATA_VENDA               493 non-null    object
 1   MODELO                   493 non-null    object
 2   KM-LITRO                 492 non-null    float64
 3   CILINDROS                493 non-null    int64
 4   PESO(KG)                 493 non-null    int64
 5   VELOCIDADE_MAXIMA(KM/H)  493 non-null    int64
 6   CAVALOS                  493 non-null    int64
 7   TRANSMISSAO              493 non-null    object
 8   VALOR                    493 non-null    object
 9   CATEGORIA                493 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 42.4+ KB

In [18]:
df_treino.head()

,DATA_VENDA,MODELO,KM-LITRO,CILINDROS,PESO(KG),VELOCIDADE_MAXIMA(KM/H),CAVALOS,TRANSMISSAO,VALOR,CATEGORIA
613,10/7/2021,CORSA,9.0,4,1900,200,118,MANUAL,35000,NACIONAL
451,10/12/2020,HB20,9.0,3,2100,200,118,MANUAL,40000,NACIONAL
731,10/9/2021,PARATI,11.0,4,2400,220,118,MANUAL,18000,NACIONAL
436,10/12/2020,HONDA FIT,12.0,4,1700,200,116,AUTOMATICO,120000,NACIONAL
275,10/9/2020,MOBI,14.0,4,1700,200,118,MANUAL,42000,NACIONAL

In [19]:
df_teste.head()

,DATA_VENDA,MODELO,KM-LITRO,CILINDROS,PESO(KG),VELOCIDADE_MAXIMA(KM/H),CAVALOS,TRANSMISSAO,VALOR,CATEGORIA
606,10/7/2021,ASTON MARTIN,3.5,10,1600,360,620,AUTOMATICO,900000,IMPORTADO
15,10/2/2020,JEEP RENEGADE,7.0,4,2200,200,210,AUTOMATICO,110000,NACIONAL
3,10/1/2020,FERRARI,3.0,12,1400,360,640,AUTOMATICO,900000,IMPORTADO
868,10/12/2021,HB20,9.0,3,2100,200,118,MANUAL,40000,NACIONAL
909,10/12/2021,PASSAT,8.0,6,1800,200,118,MANUAL,200000,IMPORTADO

In [ ]:
# Agora você tem o dataframe de treinamento (df_treino) e o dataframe de teste (df_teste)